### ISSUE TITLE
time.lua not showing time correctly

### ISSUE THREAD

**Issue by alirezaalavi87** [closebox73/Chepeus#5]
Hi.
First, Thanks for your great themes (your taste in music is also great).
I'm using the Rischa theme and at 12:49, instead of "twelve forty nine" it shows "ten two forty nine"
![image](https://github.com/closebox73/Chepeus/assets/63902085/59ee5ccb-a7ed-461e-ab9b-89b70564a81f)

**Comment by alirezaalavi87** [comment]
also happens in minutes: 
![image](https://github.com/closebox73/Chepeus/assets/63902085/7cab928c-58d7-4f33-8986-690538d25634)

**Comment by closebox73** [comment]
Oh sorry.. i will update the script

**Comment by alirezaalavi87** [comment]
Thanks!

**Comment by closebox73** [comment]
Done, Rischa already update
